### ISSUE TITLE
Shrink Ray gets stuck in `replace_bodies_with_ellipsis` at beginning of reduction

### ISSUE THREAD

**Issue by devdanzin** [DRMacIver/shrinkray#12]
The attached sample file makes Shrink Ray get stuck for hours in `replace_bodies_with_ellipsis` for me. When this happens, it pegs one CPU core and memory use seems to remain constant.

The command used to run Shrink Ray is:
```
shrinkray --parallelism 4 --timeout=120 _lsprof_abort.sh source_lsprof.py
```

Where `_lsprof_abort.sh` is:
```bash
#!/bin/bash
/home/ubuntu/projects/upstream_cpython/python ./source_lsprof.py
if ! test "$?" = "134"; then
    exit 1
else
    exit 0
fi
```

Running c-reduce works on this file, and the result of such reduction works fine in Shrink Ray.

IIUC one feature of Shrink Ray is choosing suitable passes so the start isn't too slow, so this looks like a bug.

Example output:
```
                                                                      Shrink Ray. Press q to exit.
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Current test case size: 664044 bytes
Total runtime: 3 hours, 28 minutes and 26.15 seconds
Calls to interestingness test: 380 (0.03 calls / second, 0.00% interesting, 0.00% wasted)
No reductions yet
Reducer status: Running reduction pass replace_bodies_with_ellipsis
Current parallel workers: 4 (Average 2.23) (effective parallelism: 2.23)
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```
`python -VV`:
```
Python 3.12.7+ (heads/3.12:512a5bd, Nov 20 2024, 21:38:00) [GCC 13.2.0]
```

Thank you very much for your wonderful tools and writings!
[source_lsprof.py.txt](https://github.com/user-attachments/files/18105346/source_lsprof.py.txt)

**Comment by DRMacIver** [comment]
> this looks like a bug

Yeah, this is definitely a bug. Shrinkray really shouldn't get stuck in long-running passes, particularly early on when other passes would work. Will try to investigate soon.

Is the upstream cpython you're testing against some particular commit?

**Comment by devdanzin** [comment]
> Is the upstream cpython you're testing against some particular commit?

Great question, I'll report the commit soon and see what happens in release tags.

Sorry for not checking what happens in different versions.

**Comment by devdanzin** [comment]
Sorry for the long delay, I mistakenly thought it was not reproducing and spent a lot of time reconstructing the conditions.

Turns out it was reproducing, just that my initial diagnosis was wrong: it doesn't get stuck at the first pass, but rather goes through some passes without any reduction.

For me, it went through: `delete_statements`, `replace_statements_with_pass`, `hollow`, `split(b'\n')/delete_duplicates`, `split(b'\n')/block_deletion(10, 100)`, `lift_braces`,  `remove_indents`,  `remove_whitespace`,  plus a couple more in between I didn't catch.

`upstream_cpython` is:
```
Python 3.12.8+ (heads/3.12:b0615a8a9aa, Dec 16 2024, 16:01:26) [GCC 13.3.0]
```

It only repros with 3.12 (where the CPython bug exists).

**Comment by DRMacIver** [comment]
Do you know if this CPython bug is platform specific? I've tried checking out CPython to that version and building it, but it runs your `source_lsprof.py` file just fine. Or rather it produces a tonne of error messages but exits with `0`. I'm on OSX though, so I wonder if this is a Linux-specific bug or something.

**Comment by DRMacIver** [comment]
I think I've got a reproduction anyway. Looks like the problem fails more noisily with later versions of trio, which I've now upgraded shrinkray to, and is related to my foolishly using some async generators in some code I wrote before I realised what a minefield they were. I'll try refactoring that code to use something more sensible and see if that fixes the problem.

**Comment by DRMacIver** [comment]
OK I'm not *super* confident that I've fixed the problem, but I've fixed a problem in the area that could plausibly be the same problem. If you could check if it works for you now I'd appreciate it.

**Comment by DRMacIver** [comment]
I'm going to close this, but if you run into the problem again please reopen it @devdanzin

**Comment by devdanzin** [comment]
Sorry for not being in contact for so long. Indeed, the problem isn't fixed.

I've spent a long time studying the issue and now believe there's at least an issue with `libcst_transform`, in that it makes all reductions passes that depend on it (and thus `replace_bodies_with_ellipsis`) all-or-nothing: the reduction pass will either succeed or fail based on the interestingness of the whole transformed module.

This makes code like the below (which somewhat models the original test case) impervious to `replace_bodies_with_ellipsis` when the `is_interesting` function consists of `lambda x: b"Profiler" in x`:
```python
import asyncio
import _lsprof

if True:
    a = 1
    b = 2
    c = 3

if True:
    a = 11
    b = 12
    c = 13

if True:
    obj = _lsprof.Profiler()
    obj.enable()
    obj._pystart_callback(lambda: 0, 0)
    obj = None  
    loop = asyncio.get_event_loop()

if True:
    a = 21
    b = 22
    c = 23

if True:
    a = 31
    b = 32
    c = 33

if True:
    a = 41
    b = 42
    c = 43

if True:
    a = 51
    b = 52
    c = 53

if True:
    a = 61
    b = 62
    c = 63

if True:
    a = 71
    b = 72
    c = 73
```
Even though `replace_bodies_with_ellipsis` is able to replace each indented block with `Ellipsis`, the interestingness test happens for the whole module after transformation, which will fail because the block containing `b"Profiler"` will have been replaced too.

So `replace_bodies_with_ellipsis` (and presumably all of `PYTHON_PASSES`) spends a long time parsing the 18k lines module and substituting indented blocks (of which there are a couple thousands in the original test case) only to always fail the interestingness test, because the interesting code was in an indented block.

I've modified  `libcst_transform` so that `replace_bodies_with_ellipsis` is able to reduce the code above a bit by evaluating interestingness after some replacements instead, but the PoC is incorrect/incomplete and fails to reduce the original test case: #18.

**Comment by DRMacIver** [comment]
Huh. I'll investigate. That's very weird (and bad!) if true. Thanks for the detailed investigation!

**Comment by DRMacIver** [comment]
OK. This should be fixed for real now. Such a stupid bug in the end (forgetting to update a counter in one branch of the reduction pass). Thanks for the really good example, it made it much easier to track this problem down.
